### ISSUE TITLE
Upgrade to the latest dependancies

### ISSUE THREAD

**Issue by felixcheruiyot** [felixcheruiyot/intasend_flutter#8]
Get the new webview_flutter > https://pub.dev/packages/webview_flutter

**Comment by Imesh7** [comment]
Hi @felixcheruiyot ,
I am working on this issue. I got a error.

reponse code = 400

`"type":"validation_error","errors":[{"code":"invalid","detail":"Ensure you are using the right publishable key and for the right environment. Learn more here on API testing - https://developers.intasend.com/sandbox-and-live-environments","attr":null}]}`

I think it would be the occurs due to the invalid public key,
can I get the test key to proceed?

**Comment by Imesh7** [comment]
got the key
